name:                request-header-parser-haskell
version:             0.1.0.0
github:              "AliNisarAhmed/request-header-parser-haskell"
license:             BSD3
author:              "Ali Nisar Ahmed"
maintainer:          "example@example.com"
copyright:           "2020 Ali Nisar Ahmed"

# extra-source-files:
# - README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/delete-later#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - servant-server
    - wai
    - wai-extra
    - transformers
    - mtl
    - warp
    - text
    - persistent
    - persistent-template
    - time

executables:
  request-headers-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - request-header-parser-haskell

tests:
  request-headers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - servant-server
    - wai
    - warp
